### PR TITLE
Added support for automatically generating the manifest (+some other stuff)

### PR DESCRIPTION
**Pull request by abjerner**
Hi Tom,

As a follow up to #7, I have now committed a bunch of changes:

1. Specifying a manifest is now optional. If specified, the task will now give the same result as before, and work with the Grunt template transformations that you described in #7.<br /><br />When not specifying a manifest, the task will now automatically generate the manifest based on the task configuration. The manifest is generated using `js2xmlparser` which now has been added as a dependency.

1. The documentation for `v0.0.6` says that `readme` is optional, but the task still requires a value to be entered. With this pull request, it is now optional. If specified together with `manifest`, `readme` is the path to a text file with the readme value. If `manifest` is not specified, `readme` is the string value representing the readme.

2. I have introduced a new config option called `outputName`. If specified, this will determine the name of the generated ZIP archive. If not specified, it will just be `{name}_{version}.zip` as before.

3. The existing code will create a temp directory in `sourceDir`, but not remove the directory after the task has completed, which quickly would create a mess if not manually removing the temp directory after each run. I have now updated the code not create a temp folder at all.

4. With the existing code, new files would just be appended to the ZIP file if one with the same name already existed. The task will now automatically start with deleting the ZIP file if it already exists.

5. When creating a new package via the Umbraco backoffice, files in the ZIP archive are not always named `{guid}.{ext}`. Files are typically be named `{name}.{ext}`, or if multiple files have the same name, additional files will be named `{guid}_{name}.{ext}`.

### CODE REVIEW

**Comment by tomfulton** [comment]
@abjerner Awesome Anders, thanks for all your hard work and the detailed comments!  I will spend some time reviewing this towards the end of the week and over the weekend.  I'll test it against Archetype too.  Will let you know how it goes!

**Comment by tomfulton** [comment]
@abjerner FYI, I haven't forgotten about you :), got busy over the weekend and am onsite with a client this week.  I will review and get this tested/merged next week.  Thanks again!

**Comment by abjerner** [comment]
No worries. I can work around it locally meanwhile using my own fork ;)

**Comment by tomfulton** [comment]
I spent some time reviewing this, and all of it looks great :+1:!  Thanks for # 6 as well, I'm not sure when that behavior stopped, but this is much easier to work with.

I did just have two questions:

* **Readme** - I like the idea of being able to specify a string instead of a file, but I think we should leave both options for those that don't want a huge readme in their Gruntfile, and I'm not sure it should be tied to the `manifest` option as I could see both sides using it.  Is there a way to make the option work both ways, or would we need to add a second option?  Or should it be up to to just use `grunt.file.read()` in their Gruntfile if they want to pull from a text file?

* **Manifest Backwards Compatibility** - one issue I noticed is probably just due to a [strange pattern](https://github.com/imulus/Archetype/blob/master/config/package.xml#L33) we used in Archetype, but I'm wondering if any others might be using it as well.  Basically, it determines the guid itself in the manifest template as `f.guid + f.ext`, so [this update](https://github.com/tomfulton/grunt-umbraco-package/pull/8/files#diff-e36cde92186ca4a1a80f9ae82c5f5a9dL36) is causing it to generate: `archetype.html.html` as the guid.  This results in the packager creating an empty folder structure during install.
I'm thinking we can just mark this as a "breaking" change and just release this as a new major version.  Make sense?

Also, I took a stab at updating the documentation to reflect the new options in #9 ([README](https://github.com/tomfulton/grunt-umbraco-package/blob/763038d0f1fef6ba8fff6bd6250c90ca9e5f16ad/README.md)).  I also moved `src` and `dest` to the root of the task to be more grunt-like, will look at implementing these since this will be a breaking release anyway :).

Thanks again for all of your work!

**Comment by abjerner** [comment]
#### Readme
Grunt offers good possibilities to read files, so I personally I think being able to specify a string is sufficient. As an example, for one of my packages I have defined the readme as part of `package.json`, and then read the JSON from `Gruntfile.js`:

https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/package.json
https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/Gruntfile.js#L6

With the readme defined in `package.json`, one could use it for something else as well.

#### Manifest
I haven't seen the double extensions before, and it shouldn't happen - so it is a bug. Adding an option for whether file names should just be GUIDs and the extension, or a combination of the GUID, filename and extension would make sense. I will look into fixing the bug and possibly adding the option, and then update the pull request ;)

**Comment by tomfulton** [comment]
Hi @abjerner - finally got around to pulling all of this together.  I agree with your thoughts on the readme, and decided to just treat that manifest bug as a breaking change, as we already had a few others.

So with that, v1.0 is now released!  As mentioned there are a few breaking changes which are detailed in the [CHANGELOG](https://github.com/tomfulton/grunt-umbraco-package/blob/master/CHANGELOG.md#100---11242015).  If you're able to try updating your package, that would be awesome!  I've also sent a [pull request to Archetype](https://github.com/imulus/Archetype/pull/308/files) to upgrade and remove the package.xml - good stuff!

Thanks again for all of your help, this is awesome! #h5yr

**Comment by abjerner** [comment]
Awesome. I have been super busy, so I hadn't gotten around looking at the issues myself. I will try to find some time for testing v1.0 ;)

**Comment by abjerner** [comment]
Tested it for a few of my packages, and it works splendid :+1:

**Pull request merged**
